
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: org.xi.quick.codebuilder.mapper
spring:
  datasource:
    url: jdbc:mysql://192.168.10.22:3306/information_schema?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&rewriteBatchedStatements=true&useServerPrepStmts=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: cy_ec_admin
    password: 1qaz@WSX
    driver-class-name: com.mysql.jdbc.Driver





